"""
sleep_coach.py — RestIQ Cognitive Science Engine

Evidence-based sleep coaching grounded in:
- Borbély's Two-Process Model (Process S: sleep pressure, Process C: circadian rhythm)
- Van Dongen et al. (2003): cumulative sleep debt and cognitive impairment
- Walker (2017): sleep architecture and habit impact
- Roenneberg et al.: chronotype and social jetlag
- Harvard Medical School: sleep hygiene evidence base

This module replaces generic recommendations with personalized,
science-grounded advice based on the user's actual habit pattern.

The user-facing message is generated by Gemini for a warm, conversational
tone, grounded strictly in the computed CoachingResult (no hallucinated
facts). If Gemini is unavailable (quota exceeded, network error, missing
key, etc.), get_coaching_message() automatically falls back to the
deterministic hardcoded template so check-ins never fail.
"""

from __future__ import annotations
import os
import logging
import datetime
from dataclasses import dataclass
from typing import Optional
from schemas import SleepEntrySchema, SleepAnalysisSchema, SleepQuality, MoodOnWake

logger = logging.getLogger("sleep_coach")

# ──────────────────────────────────────────────────────────────────────────────
# Gemini client (lazy init, optional — module works fine without it)
# ──────────────────────────────────────────────────────────────────────────────

_GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
_client = None
_gemini_import_error = None

try:
    from google import genai  # NOTE: confirm this matches tools/intake.py's import
    api_key = os.environ.get("GOOGLE_API_KEY")
    if api_key:
        _client = genai.Client(api_key=api_key)
    else:
        _gemini_import_error = "GOOGLE_API_KEY not set"
except Exception as e:  # pragma: no cover - defensive, import may differ per SDK version
    _gemini_import_error = str(e)


# ──────────────────────────────────────────────────────────────────────────────
# Science constants
# ──────────────────────────────────────────────────────────────────────────────

# Caffeine half-life is ~5-6 hours (Nehlig et al., 1992)
# Caffeine after 2PM = still ~50% active at 10PM
CAFFEINE_HALFLIFE_HOURS = 5.5

# Blue light suppresses melatonin by up to 50% for ~3h after exposure
# (Harvard Health, Gooley et al. 2011)
SCREEN_MELATONIN_SUPPRESSION_HOURS = 3

# Optimal sleep window for adults: 7-9 hours (NSF, 2015)
OPTIMAL_SLEEP_MIN = 7.0
OPTIMAL_SLEEP_MAX = 9.0

# Sleep debt accumulates linearly; >1h deficit per night degrades reaction
# time equivalent to 0.05% BAC per 24h awake (Van Dongen et al., 2003)
DEBT_IMPAIRMENT_THRESHOLD = 1.0  # hours below optimal per night

# Wind-down window: 60-90 min before bed (Walker, 2017)
WIND_DOWN_MINUTES = 75

# Chronotype-aware bedtime ranges (Roenneberg et al.)
CHRONOTYPE_RANGES = {
    "early": ("21:00", "22:30"),   # "morning larks"
    "intermediate": ("22:30", "00:00"),  # majority
    "late": ("00:00", "01:30"),    # "night owls"
}


# ──────────────────────────────────────────────────────────────────────────────
# Data classes
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class SleepDebtResult:
    total_debt_hours: float
    nightly_deficit: float
    impairment_level: str   # NONE, MILD, MODERATE, SEVERE
    cognitive_note: str


@dataclass
class CoachingResult:
    recommended_bedtime: str
    wind_down_start: str
    screen_cutoff: str
    caffeine_cutoff: str
    primary_insight: str          # The #1 thing affecting their sleep
    personalized_tips: list[str]  # 2-3 specific, science-backed tips
    sleep_debt: SleepDebtResult
    chronotype_note: str


# ──────────────────────────────────────────────────────────────────────────────
# Core functions
# ──────────────────────────────────────────────────────────────────────────────

def _hhmm_to_minutes(hhmm: str) -> int:
    h, m = map(int, hhmm.split(":"))
    return h * 60 + m


def _minutes_to_hhmm(minutes: int) -> str:
    minutes = int(minutes) % (24 * 60)
    return f"{minutes // 60:02d}:{minutes % 60:02d}"


def _compute_sleep_debt(
    entries: list[SleepEntrySchema],
    target_duration: float = 8.0
) -> SleepDebtResult:
    """
    Computes cumulative sleep debt over the last N nights.
    Based on Van Dongen et al. (2003) chronic sleep restriction model.
    """
    if not entries:
        return SleepDebtResult(0, 0, "NONE", "No history yet.")

    deficits = [max(0, target_duration - e.sleep_duration) for e in entries]
    total_debt = sum(deficits)
    nightly_avg = total_debt / len(deficits)

    if total_debt < 1.0:
        level = "NONE"
        note = "Your sleep debt is minimal. Maintain consistency."
    elif total_debt < 3.0:
        level = "MILD"
        note = (
            f"You've accumulated ~{total_debt:.1f}h of sleep debt this week. "
            "Mild impairment in attention and reaction time is likely. "
            "One extra hour tonight helps."
        )
    elif total_debt < 7.0:
        level = "MODERATE"
        note = (
            f"~{total_debt:.1f}h sleep debt detected. This is equivalent to "
            "the cognitive impairment of mild alcohol intoxication. "
            "You likely underestimate how impaired you are."
        )
    else:
        level = "SEVERE"
        note = (
            f"⚠️ ~{total_debt:.1f}h sleep debt. Severe cognitive impairment: "
            "reaction time, memory consolidation, and emotional regulation "
            "are all significantly degraded. Prioritize sleep this weekend. "
            "Recovery requires multiple full nights, not just one."
        )

    return SleepDebtResult(total_debt, nightly_avg, level, note)


def _infer_chronotype(wake_time: str) -> tuple[str, str]:
    """
    Infers rough chronotype from habitual wake time.
    Based on Roenneberg et al. (2007) Munich Chronotype Questionnaire.
    Returns (chronotype, note).
    """
    wake_min = _hhmm_to_minutes(wake_time)

    if wake_min <= _hhmm_to_minutes("06:30"):
        return "early", "You're a morning chronotype (lark). Your ideal bedtime is 9-10:30PM."
    elif wake_min <= _hhmm_to_minutes("08:00"):
        return "intermediate", "You have an intermediate chronotype. Ideal bedtime: 10:30PM-midnight."
    else:
        return "late", (
            "You appear to be a late chronotype (owl). "
            "Your natural bedtime is later, but social obligations create 'social jetlag' "
            "if your schedule forces an early wake. "
            "Gradual 15-min earlier shifts work better than sudden changes."
        )


def _identify_primary_culprit(entry: SleepEntrySchema, analysis: Optional[SleepAnalysisSchema] = None) -> str:
    """
    Identifies the single biggest factor degrading sleep quality,
    with the science explanation attached.
    """
    factors = []

    if entry.screen_time_before_bed:
        factors.append((
            20,
            "📱 Screen time before bed is your biggest issue. "
            "Blue light suppresses melatonin production by up to 50% "
            "for 2-3 hours after exposure. "
            "Your brain literally can't prepare for sleep while you're on your phone."
        ))

    if entry.caffeine_after_2pm:
        factors.append((
            15,
            "☕ Late caffeine is disrupting your sleep architecture. "
            "With a ~5.5h half-life, caffeine consumed at 3PM is still ~35% active at midnight. "
            "It reduces deep (slow-wave) sleep even when you feel like you slept fine. "
            "Cut off by 1PM to be safe."
        ))

    if entry.wake_up_count >= 3:
        factors.append((
            12,
            f"🌙 Waking up {entry.wake_up_count}x disrupts your sleep cycles. "
            "Each 90-min sleep cycle ends in brief arousal. "
            "More than 2 wake-ups suggests your sleep pressure is low, "
            "your sleep environment is disrupted, or alcohol/hydration is a factor."
        ))

    if entry.sleep_duration < OPTIMAL_SLEEP_MIN:
        deficit = OPTIMAL_SLEEP_MIN - entry.sleep_duration
        factors.append((
            18,
            f"⏰ You only got {entry.sleep_duration}h — {deficit:.1f}h below the 7h minimum. "
            "Sleep is not optional recovery: memory consolidation, immune function, and "
            "emotional regulation all require sufficient slow-wave and REM sleep. "
            "There is no 'catching up' on weekdays."
        ))

    if entry.mood_on_wake in [MoodOnWake.TIRED, MoodOnWake.TERRIBLE]:
        if not factors:
            factors.append((
                8,
                "😴 You're waking up tired despite no obvious habit red flags. "
                "Try shifting your alarm 20-30 minutes earlier or later "
                "to land in lighter sleep (N1/N2) instead."
            ))

    if not factors:
        return (
            "✅ No strong negative habits detected tonight. "
            "Consistency is your best tool — same bedtime and wake time every day, "
            "even weekends, anchors your circadian rhythm."
        )

    factors.sort(key=lambda x: x[0], reverse=True)
    return factors[0][1]


def _build_personalized_tips(entry: SleepEntrySchema, chronotype: str) -> list[str]:
    """
    Builds 2-3 specific, actionable, science-backed tips
    based on the user's actual habits tonight.
    """
    tips = []

    if entry.screen_time_before_bed:
        tips.append(
            "🔴 Set a phone cutoff 75 minutes before your target bedtime. "
            "Use blue-light blocking glasses or Night Mode as a fallback, "
            "but physical separation works better."
        )
    else:
        tips.append(
            "✅ Good: no screens before bed. Keep this up — "
            "it's one of the highest-leverage sleep hygiene behaviors."
        )

    if entry.caffeine_after_2pm:
        tips.append(
            "🔴 Move your last caffeine to before 1PM tomorrow. "
            "If you rely on afternoon caffeine for energy, that's a sign "
            "of sleep debt — the solution is more sleep, not more caffeine."
        )

    if not entry.exercise_today:
        tips.append(
            "💪 Even 20 minutes of aerobic exercise increases slow-wave sleep "
            "by ~15%. Morning or afternoon is ideal — "
            "intense exercise within 3h of bed can delay sleep onset."
        )
    elif entry.exercise_today and entry.sleep_quality in [SleepQuality.POOR, SleepQuality.FAIR]:
        tips.append(
            "🕐 You exercised today but still slept poorly — check timing. "
            "Late-evening intense exercise raises core body temperature and cortisol, "
            "delaying sleep onset by 30-60 minutes."
        )

    if chronotype == "late" and entry.wake_time:
        tips.append(
            "🦉 As a late chronotype, avoid dramatic weekend sleep-ins. "
            "Sleeping 2+ hours later on weekends causes 'social jetlag' — "
            "equivalent to flying across 2 time zones every week. "
            "Max 30-min deviation from your weekday wake time."
        )

    return tips[:3]  # Max 3 tips to avoid overwhelm


def _compute_smart_bedtime(
    wake_time: str,
    sleep_debt: SleepDebtResult,
    chronotype: str,
    screen_before_bed: bool,
    caffeine_after_2pm: bool,
) -> tuple[str, str, str, str]:
    """
    Computes a science-grounded recommended bedtime, accounting for:
    - Target sleep duration (8h + debt recovery buffer)
    - Chronotype-appropriate range
    - Wind-down window (75 min before bed: no screens, no caffeine)
    - Sleep pressure (Process S of Borbély's two-process model)

    Returns (bedtime, wind_down_start, screen_cutoff, caffeine_cutoff)
    """
    wake_min = _hhmm_to_minutes(wake_time)

    target_duration_min = int(OPTIMAL_SLEEP_MIN * 60)

    if sleep_debt.impairment_level in ["MODERATE", "SEVERE"]:
        recovery_buffer = 30
    elif sleep_debt.impairment_level == "MILD":
        recovery_buffer = 15
    else:
        recovery_buffer = 0

    raw_bedtime_min = wake_min - target_duration_min - recovery_buffer

    chrono_start, chrono_end = CHRONOTYPE_RANGES[chronotype]
    chrono_start_min = _hhmm_to_minutes(chrono_start)
    chrono_end_min = _hhmm_to_minutes(chrono_end)

    if chrono_end_min < chrono_start_min:
        chrono_end_min += 24 * 60

    if raw_bedtime_min < chrono_start_min - 30:
        recommended_bedtime_min = chrono_start_min - 15
    elif raw_bedtime_min > chrono_end_min + 30:
        recommended_bedtime_min = raw_bedtime_min
    else:
        recommended_bedtime_min = raw_bedtime_min

    wind_down_min = recommended_bedtime_min - WIND_DOWN_MINUTES
    screen_cutoff_min = recommended_bedtime_min - int(SCREEN_MELATONIN_SUPPRESSION_HOURS * 60)
    caffeine_cutoff_min = _hhmm_to_minutes("13:00")  # Science-based: 1PM cutoff

    return (
        _minutes_to_hhmm(recommended_bedtime_min),
        _minutes_to_hhmm(wind_down_min),
        _minutes_to_hhmm(screen_cutoff_min),
        _minutes_to_hhmm(caffeine_cutoff_min),
    )


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

def generate_coaching(
    entry: SleepEntrySchema,
    history: list[SleepEntrySchema],
    analysis: Optional[SleepAnalysisSchema] = None,
    target_wake_time: str = "07:00",
) -> CoachingResult:
    """
    Main entry point. Generates personalized, science-backed sleep coaching
    based on last night's entry and recent history.
    """
    wake_time = entry.wake_time or target_wake_time
    chronotype, chronotype_note = _infer_chronotype(wake_time)
    sleep_debt = _compute_sleep_debt(history or [entry])
    primary_insight = _identify_primary_culprit(entry, analysis)
    tips = _build_personalized_tips(entry, chronotype)

    bedtime, wind_down, screen_cutoff, caffeine_cutoff = _compute_smart_bedtime(
        wake_time=wake_time,
        sleep_debt=sleep_debt,
        chronotype=chronotype,
        screen_before_bed=entry.screen_time_before_bed,
        caffeine_after_2pm=entry.caffeine_after_2pm,
    )

    return CoachingResult(
        recommended_bedtime=bedtime,
        wind_down_start=wind_down,
        screen_cutoff=screen_cutoff,
        caffeine_cutoff=caffeine_cutoff,
        primary_insight=primary_insight,
        personalized_tips=tips,
        sleep_debt=sleep_debt,
        chronotype_note=chronotype_note,
    )


def format_coaching_message(coaching: CoachingResult) -> str:
    """
    Deterministic hardcoded template. Always available, zero external
    dependencies. Used as the fallback when Gemini is unavailable.
    """
    return format_coaching_message_conversational(coaching)


def format_coaching_message_conversational(
    coaching: CoachingResult,
    user_context: str = "",
) -> str:
    """
    Formats CoachingResult with a warmer, conversation-aware tone.
    """
    debt_emoji = {
        "NONE": "🟢",
        "MILD": "🟡",
        "MODERATE": "🟠",
        "SEVERE": "🔴",
    }.get(coaching.sleep_debt.impairment_level, "⚪")

    tips_text = "\n".join(f"  {i+1}. {t}" for i, t in enumerate(coaching.personalized_tips))

    opener = ""
    if user_context.strip():
        opener = f"{user_context.strip()}\n\n"

    insight_header = "" if opener else "Here's what I'm seeing 👀\n\n"

    return (
        f"{opener}"
        f"{insight_header}"
        f"{coaching.primary_insight}\n\n"
        f"*Tonight's plan:*\n"
        f"  • Last coffee by {coaching.caffeine_cutoff}\n"
        f"  • Phone away by {coaching.screen_cutoff}\n"
        f"  • Start winding down at {coaching.wind_down_start}\n"
        f"  • Lights out at {coaching.recommended_bedtime}\n\n"
        f"{debt_emoji} Sleep debt: *{coaching.sleep_debt.impairment_level.title()}*\n"
        f"{coaching.sleep_debt.cognitive_note}\n\n"
        f"*A few things to try tonight:*\n{tips_text}\n\n"
        f"{coaching.chronotype_note}"
    )


def _format_coaching_message_llm(coaching: CoachingResult) -> str:
    """
    Generates a warm, conversational coaching message via Gemini, grounded
    strictly in the computed CoachingResult data (no hallucinated facts).
    Raises on any failure — caller (get_coaching_message) handles fallback.
    """
    if _client is None:
        raise RuntimeError(f"Gemini client not available: {_gemini_import_error}")

    prompt = f"""
You are a warm, encouraging sleep coach texting a friend. Write a short,
conversational message (max 120 words) using ONLY these facts — don't invent
numbers or studies:

- Main issue: {coaching.primary_insight}
- Tonight's schedule: caffeine cutoff {coaching.caffeine_cutoff}, screen cutoff
  {coaching.screen_cutoff}, wind-down {coaching.wind_down_start}, bedtime
  {coaching.recommended_bedtime}
- Sleep debt level: {coaching.sleep_debt.impairment_level} — {coaching.sleep_debt.cognitive_note}
- Tips: {coaching.personalized_tips}
- Chronotype: {coaching.chronotype_note}

Tone: casual, supportive, like a text from a friend who happens to know sleep
science. No headers, no bullet lists, no citations. Use 1-2 emoji max.
"""
    response = _client.models.generate_content(model=_GEMINI_MODEL, contents=prompt)
    text = (response.text or "").strip()
    if not text:
        raise RuntimeError("Gemini returned an empty response")
    return text


def get_coaching_message(coaching: CoachingResult, user_context: str = "") -> str:
    """
    Public entry point for the user-facing coaching message.

    Tries Gemini first for a conversational tone. On ANY failure — quota
    exceeded, rate limit, network error, missing API key, empty response —
    silently falls back to the deterministic template so a check-in never
    breaks.
    """
    try:
        text = _format_coaching_message_llm(coaching)
        if user_context.strip():
            return f"{user_context.strip()}\n\n{text}"
        return text
    except Exception as e:
        logger.warning("[SLEEP_COACH] Gemini coaching message failed, using fallback template: %s", e)
        return format_coaching_message_conversational(coaching, user_context)


if __name__ == "__main__":
    from agents.analyzer import seed_test_data
    from agents.tracker import run_get_latest, run_get_history

    test_user = "sleep_coach_test_user"
    seed_test_data(test_user)
    entry = run_get_latest(test_user)
    history = run_get_history(test_user, days=7)

    coaching = generate_coaching(entry, history)

    print("\n--- LLM path (falls back automatically if Gemini fails) ---")
    print(get_coaching_message(coaching))

    print("\n--- Hardcoded template (always available) ---")
    print(format_coaching_message(coaching))
